spring:
    application:
        name: ComplexTechnology

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/data
        username: user
        password: password
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        change-log: classpath:db/changelog/master.xml
        enabled: true
